<?php

/**
 * Implements hook_theme().
 */

function custom_api_consumer_preprocess_page(&$variables) {
  $variables['#attached']['library'][] = 'custom_api_consumer/custom-css';
}

function custom_api_consumer_theme($existing, $type, $theme, $path) {
  return [
    'custom_api_consumer_template' => [
      'variables' => ['data' => [],],
      'template' => 'custom-api-consumer-template',
    ], 
  ];
}

